AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/24

  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache
      SubnetIds:
        - !Ref MySubnet

  MyElasticacheRedis:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      CacheSubnetGroupName: !Ref MyElasticacheSubnetGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0

  # Function to handle POST requests for sending payments
  SendPaymentFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: index.sendPaymentHandler
      Runtime: nodejs14.x
      CodeUri: ./lambda
      MemorySize: 128
      Timeout: 30

  # Function to handle GET requests for payment by ID
  GetPaymentFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.getPaymentHandler
      Runtime: nodejs14.x
      CodeUri: ./lambda
      MemorySize: 128
      Timeout: 30

  # Function to handle GET requests for payments per customer
  GetPaymentsPerCustomerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.getPaymentsPerCustomerHandler
      Runtime: nodejs14.x
      CodeUri: ./lambda
      MemorySize: 128
      Timeout: 30

  # Function to handle POST requests for orders
  AddOrderFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.addOrderHandler
      Runtime: nodejs14.x
      CodeUri: ./lambda
      MemorySize: 128
      Timeout: 30

  # Function to handle GET requests for orders by ID
  GetOrderFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.getOrderHandler
      Runtime: nodejs14.x
      CodeUri: ./lambda
      MemorySize: 128
      Timeout: 30

  # Function to handle POST requests for order items
  AddOrderItemFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.addOrderItemHandler
      Runtime: nodejs14.x
      CodeUri: ./lambda
      MemorySize: 128
      Timeout: 30
